Sprint 3
octomine/middle.messenger.praktikum.yandex pull request #18
Opened 2022-09-24 11:07 UTC by octomine

2022-09-24 11:09 UTC, octomine commented
тесты разрешили в этом спринте не писать, а писать их в 4 спринте

2022-09-24 14:59 UTC, podlovchenko requested changes
Привет)
1. Не получилось запустить приложение локально
<img width="1268" alt="Снимок экрана 2022-09-24 в 17 53 13" src="https://user-images.githubusercontent.com/22602747/192104664-f02eca54-9d25-4620-8162-8b1ae08c165d.png">
2. При обновлении страницы на нетлифае Page not found
3. Нет возможности закрыть модальное окно по кнопке или esc

2022-09-24 14:59 UTC, podlovchenko commented on src/components/common/block/Block.ts
> +  protected props: any;
```suggestion
  protected props: P;
```

2022-09-24 14:59 UTC, podlovchenko commented on src/components/common/block/Block.ts
> +  private _componentDidUpdate(oldProps: object, newProps: object) {
Типы пропсов должны быть типом, который передается в класс
```suggestion
  private _componentDidUpdate(oldProps: P, newProps: P) {
```

2022-09-24 15:56 UTC, octomine commented
а по поводу не запустить локально, есть подробности какие? просто npm run start? у меня работает, не воспроизводится ((

2022-09-24 20:21 UTC, octomine commented
привет )
на нетлифае редиректы настроил
попап закрывается кнопкой с крестиком справа сверху
типы в componentDidUpdate в порядок привёл
а вот по поводу не запускается локально, не сумел воспроизвести (( попробовал даже склонировать репу на другом компе и npm i и npm start норм всё запустилось, даже и думать теперь в какую сторону не знаю

2022-09-25 06:43 UTC, podlovchenko commented
Видимо на моей стороне проблема, на нетлифае все хорошо, работу принимаю)

2022-09-25 08:45 UTC, merged

2022-09-25 08:47 UTC, octomine commented
Спасибо))
и прошу прощения за оффтоп, но ты случаем не знакома с Варей Фёдоровой?